### ISSUE TITLE
Have you tried this on Java 8u60 yet?

### ISSUE THREAD

**Issue by christopherlakey** [maximenajim/java-vs-node-react-rendering-microbenchmark#1]
Thanks for posting these tests!  It looks like Java 8u60 has some Nashorn updates.  Would be interested to see if the number have improved.

**Comment by maximenajim** [comment]
Take a look at the results for Java 8u60 here: https://github.com/maximenajim/java-vs-node-react-rendering-microbenchmark#running-with-java-180_60

BTW, the JDK team is fixing the react.js performance regression: https://bugs.openjdk.java.net/browse/JDK-8134403 - should be available as soon as 8u66.

**Comment by christopherlakey** [comment]
Thanks.  I must have missed that.
